# Generated by Django 4.1.7 on 2023-02-23 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='read',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='readtext',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
