# Generated by Django 4.1.7 on 2023-02-26 12:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boardapp', '0003_alter_boardmodel_good_alter_boardmodel_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_price', models.PositiveIntegerField()),
                ('end_time', models.DateTimeField(default=datetime.datetime(2023, 3, 5, 12, 19, 3, 837381))),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
