# Generated by Django 4.1.7 on 2023-02-27 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='start_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='null', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 2, 35, 58, 973995)),
        ),
    ]
