# Generated by Django 4.1.7 on 2023-02-27 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_rename_start_price_product_price_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 2, 44, 5, 689402)),
        ),
    ]
