# Generated by Django 4.1.7 on 2023-02-27 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0007_alter_product_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 6, 2, 51, 26, 866772), null=True),
        ),
    ]
