# Generated by Django 4.1.7 on 2023-02-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0011_product2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product2',
            name='image',
            field=models.ImageField(blank=True, default='no_image.jpeg', null=True, upload_to='product_images'),
        ),
    ]
