# Generated by Django 4.1.7 on 2023-02-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0012_alter_product2_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='no_image.jpeg', null=True, upload_to='product_images'),
        ),
    ]
