# Generated by Django 4.1.7 on 2023-03-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0014_product_bid_name_product_buyer_product_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
