# Generated by Django 4.1.7 on 2023-03-06 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boardapp', '0015_alter_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buyer',
        ),
        migrations.AddField(
            model_name='product',
            name='buyers',
            field=models.ManyToManyField(blank=True, null=True, related_name='bought_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
