# Generated by Django 4.1.7 on 2023-03-06 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boardapp', '0016_remove_product_buyer_product_buyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
